### PR TITLE
[WIP] F# signature gen for members, attributes, records, DUs, and Enums

### PR DESCRIPTION
**Pull request by cartermp**
Due to #308  I cannot test this (the test projects do not build for me), so here's to hoping that something useful comes out of CI!

Taking on:

#319 
#318 
#335
#337 
#339

### CODE REVIEW

**Comment by cartermp** [comment]
@joelmartinez I've got this now to a point where I think it's good enough to do acceptance testing, but the build still fails after tests pass. Any ideas?

**Comment by cartermp** [comment]
Ah durn, looks like there's some XML baselines that need updating. Can a tool do that?

**Comment by joelmartinez** [comment]
@cartermp not really in this case (_some_ of those integration tests have ways to automatically update them in cases of breaking changes like this ... but it has to be done via CLI/make, and these f# tests in particular don't have those targets).

I'm working on a few high-pri things right now, but am going to try to make some time today or tomorrow to look at why this isn't building on windows, in addition to making the requisite edits to the test XMLs. Just grant me the ability to modify your branch:  
https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by cartermp** [comment]
@joelmartinez according to the article you should have rights to edit the branch.

**Comment by cartermp** [comment]
@joelmartinez I added a new file, and the project builds locally, but not on CI. The file is a part of these changes. Is there something else I need to do to make it build in CI?

**Comment by cartermp** [comment]
never mind, it's old style csproj

**Comment by joelmartinez** [comment]
@cartermp I'm now working on updating the baseline XML tests ... I've encountered one regression. Looks like you updated the generic parameter brackets to use `{` instead of `<`; however you've done so in a place that affected some of the other formatters (not sure offhand if it's the docid formatter, or the slashdoc formatter, in this case):

```
-      <Member Id="P:Mono.DocTest.Generic.MyList`2.System#Collections#Generic#ICollection&lt;A&gt;#IsReadOnly" />
-      <Member Id="P:Mono.DocTest.Generic.MyList`2.System#Collections#Generic#IEnumerator&lt;A&gt;#Current" />
+      <Member Id="P:Mono.DocTest.Generic.MyList`2.System#Collections#Generic#ICollection{A}#IsReadOnly" />
+      <Member Id="P:Mono.DocTest.Generic.MyList`2.System#Collections#Generic#IEnumerator{A}#Current" />
```

This would end up breaking a large amount of systems that depend on the current formatting for those IDs

**Comment by mimisasouvanh** [comment]
[Internal work item](https://ceapex.visualstudio.com/Engineering/_workitems/edit/163531) created to track this bug

**Comment by joelmartinez** [comment]
This work has unfortunately bit-rotted past the point where it is possible to reasonably re-integrate it with the latest code ... I'm going to close this PR, though we will keep it for reference if/when we have resources in the future to address some of these issues.

**Pull request closed without merging**
