### PR TITLE
mdoc: Support for attached events

### LINKED ISSUE #63: [mdoc] No support for attached events
Currently, `mdoc` does not support treating attached events as members, which causes loss of data when reflecting from .NET assemblies.

As an example of an attached event:
https://msdn.microsoft.com/en-us/library/system.windows.dragdrop.dragover(v=vs.110).aspx

### PR DESCRIPTION
**Pull request by mpMelnikov**
Added AttachedEventReference, AttachedEventDefinition, AttachedPropertyReference, AttachedPropertyDefinition (equivalents of Cecil entities)
They are processed as any other Cecil entities
Added check-monodocer-attached-entities integration test
Closes #63

### CODE REVIEW

**Comment by mpMelnikov** [comment]
It is a work in progress pull request. Just want to ask a couple of questions.

**Comment by mpMelnikov** [comment]
@joelmartinez 
1. To detect attached properties I've used the rules proposed in this [comment](https://github.com/mono/api-doc-tools/issues/63#issuecomment-328995418). 
There is such an idea:
> The Get method ... returns a value of type dp.PropertyType (or IsAssignableTo…), where dp is the value of the static field.

As you can see, it is proposed to check the value of the property `public Type PropertyType`. Correct me if I'm wrong, but to check it we should get an instance of a declaring type, and it doesn't seem to be a doable task with Cecil. Maybe we can just check the rest of the rules ([names, other types checks](https://github.com/mono/api-doc-tools/pull/165/commits/7cbc66c1b6d0655918695a8edd723f5cb61826b2?diff=unified#diff-f2d972d04beff3353a928371c7abcc5b))?

2. There was a [proposal](https://github.com/mono/api-doc-tools/issues/63#issuecomment-331831890) to re-use the existing prefixes (E: for the attached event and P:
for attached properties). Should I do something to re-use them? How can I check that these prefixes are generated for attached events and properties?

3. As this feature is tightly coupled with WPF, to compile a code sample with `AttachedProperty` and other classes we have to add the dependency on `PresentationFramework.dll`. To avoid this, I've [declared types](https://github.com/mono/api-doc-tools/pull/165/commits/7cbc66c1b6d0655918695a8edd723f5cb61826b2?diff=unified#diff-99b92dfa95192dce8187c51d72330e43) with the same names and namespaces in the test project, so, all checks of names just work. Is it an appropriate approach?

**Comment by joelmartinez** [comment]
@mpMelnikov 

1. Hmm, I'm afraid I don't understand what you're asking ... why is there a problem acquiring the declaring type for any given member?
2. This is referring to the DocID ... I guess this is something that we didn't really discuss, that we'll have to generate a signature for every formatter out there for these `Member` nodes that don't actually exist as a `MemberDefinition`/`MemberReference`. 
    - Do we need to have signatures in these at all, since they're a xaml thing? @dend ?
    - Do you have any thoughts/proposals about how to handle this? 
    - If we have to add signatures, we _might_ have to just have special abstract methods added to the base `MemberFormatter` for both attached events and properties ... and then include an implementation of them in each language formatter.
3. I'm ok with this ... smart solution :)

One other tiny bit of feedback

```csharp
field.DeclaringType.Methods.Any(i => IsAttachedEventMethod(i, $"Add{GetEventName(field.Name)}Handler"));
field.DeclaringType.Methods.Any(i => IsAttachedEventMethod(i, $"Remove{GetEventName(field.Name)}Handler"));
```
Please avoid using `.Any` in this context ... If you consider the performance implications here, this is just doing a simple linear search (`O(n)`). So if the type has a lot of members it could be quite detrimental to performance. 

We need to consider building a lookup table that we can pass into any methods that need to look up members by name ... not sure what else is going on in `IsAttachedEventMethod`.

**Comment by mpMelnikov** [comment]
@joelmartinez 
1. Maybe it will be better if I show an example.
```
public static readonly DependencyProperty IsBubbleSourceProperty = DependencyProperty.RegisterAttached(
  "IsBubbleSource",
  typeof(Boolean),
  typeof(AquariumObject),
  new FrameworkPropertyMetadata(false, FrameworkPropertyMetadataOptions.AffectsRender)
);
public static void SetIsBubbleSource(UIElement element, Boolean value)
{
  element.SetValue(IsBubbleSourceProperty, value);
}
public static Boolean GetIsBubbleSource(UIElement element)
{
  return (Boolean)element.GetValue(IsBubbleSourceProperty);
}
```
So, we should check `IsBubbleSourceProperty.PropertyType` **runtime** value. In this example, it is `typeof(Boolean)`

2. 
> Do you have any thoughts/proposals about how to handle this?

If you talk about general architecture, I've already committed my proposal:) There are `AttachedEventReference`, `AttachedEventDefinition`, `AttachedPropertyReference`, `AttachedPropertyDefinition` classes. Their instances are generated in `CecilExtensions.GetMembers` method.
But if you talk specifically about DocId, I have not yet investigated this topic. 

> If we have to add signatures, we might have to just have special abstract methods added to the base `MemberFormatter`

I've added `GetAttachedEventDeclaration` and `GetAttachedPropertyDeclaration` virtual methods to MemberFormatter. At the moment, they are not overridden in other formatters because in MSDN [we see](https://msdn.microsoft.com/en-us/library/system.windows.dragdrop.dragover(v=vs.110).aspx?cs-save-lang=1&cs-lang=fsharp#code-snippet-1) "See Add[Name]Handler, Remove[Name]Handler" signature for all languages.

**Comment by mpMelnikov** [comment]
@joelmartinez
> Please avoid using .Any in this context ... 
We need to consider building a lookup table 

Thank you for a good idea! I've added a lookup table, so we iterate all methods just once:
```
private static Dictionary<string, IEnumerable<MethodDefinition>> GetMethodsLookUpTable(TypeDefinition type)
{
    return type.Methods.GroupBy(i => i.Name, i => i).ToDictionary(i => i.Key, i => i.AsEnumerable());
}
```
There is still a call of `.Any` method, but the list `methods[methodName]` contains more than one item only if there are methods with the same name and all other checks returned true.
```
                && methods.ContainsKey(addMethodName)//O[1]
                && methods.ContainsKey(removeMethodName)//O[1]
                && methods[addMethodName].Any(IsAttachedEventMethod)
                && methods[removeMethodName].Any(IsAttachedEventMethod);
```

**Comment by dend** [comment]
@joelmartinez looking at MSDN, short of having the DocID, we might not need any other signatures for it. @mairaw to confirm that attached events across the board do not need signatures.

**Comment by mpMelnikov** [comment]
@joelmartinez If we don't need to do something else for DocID, this pull request seems to be ready for review.

**Comment by mpMelnikov** [comment]
@joelmartinez I've added DocId support the way you suggested and it looks good:) Also, I've refactored new classes a little bit.

**Comment by joelmartinez** [comment]
@mpMelnikov nice! hah, honestly I'm surprised that the slashdoc formatter didn't require any changes to support this.

> They will support it out of the box because MemberFormatter has basic implementation of `GetAttachedEventDeclaration` and `GetAttachedPropertyDeclaration` methods.

**Comment by mpMelnikov** [comment]
@joelmartinez Well, slashdoc formatter required to override `GetAttachedEventDeclaration` and `GetAttachedPropertyDeclaration` methods, but I hope the other language formatters will not need changes:) The last commit is rebased.

**Pull request merged**
