### PR TITLE
 Enabling Guid type projection for C++/WinRT and C++/CX.

### PR DESCRIPTION
**Pull request by JeffInChrist**
Since Windows 10, version 1809 GUID has been a fundemental type in UWP. With these changes the API's regarding GUID will be projected in C++/WinRT and C++/CX. The API signatures will be updated, enabling the language picker for the 2 languages. 

For instance, Windows.Foundation.GuidHelper.Equals(Guid, Guid) will be updated with new syntax:
C++ WINRT | " static bool Equals(winrt::guid target, winrt::guid value);"
C++ CX | "public:&#xA; static bool Equals(Platform::Guid target, Platform::Guid value);"

Related Work Item:
https://dev.azure.com/ceapex/Engineering/_workitems/edit/344653

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/mono/api-doc-tools?pullRequest=546) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/mono/api-doc-tools?pullRequest=546) before we can accept your contribution.<br/><br/>:x: JeffInChrist [sign now](https://cla.dotnetfoundation.org/mono/api-doc-tools?pullRequest=546)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/mono/api-doc-tools?pullRequest=546) it.</sub>

**Comment by JeffInChrist** [comment]
@joelmartinez @anmeng10101 Can you please review my changes? The unit tests ran successfully on my side.

**Comment by anmeng10101** [comment]
@JeffInChrist the Integration Tests failed, please check the pipeline for more details and fix.

**Comment by JeffInChrist** [comment]
@anmeng10101 Well, I've fixed the Integration Tests. Thanks Ann.

Additionally, my changes are intended to enable GUID type projection. Shall I add some tests to cover it?

**Comment by anmeng10101** [comment]
@JeffInChrist please check the formatter tests under https://github.com/mono/api-doc-tools/tree/develop/mdoc/mdoc.Test, and add new cases accordingly.

**Comment by JeffInChrist** [comment]
@anmeng10101 @joelmartinez I have added unit tests and integration tests for the new Type of Guid. The test results look good to me. But I am not sure if it meets the coding standard or it might cause any other potential issue. Can you pls review my changes?

**Review by joelmartinez — APPROVED** [review]
This looks great ... thanks for adding the integration tests. Also, for fixing the spacing bug :D

**Pull request merged**
