### PR TITLE
[mdoc] Set `RollForward` to `Major`

### PR DESCRIPTION
**Pull request by pjcollins**
Context: https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#rollforward

Allows the `net6.0` version of mdoc to run against newer dotnet runtime
versions, rather than requiring `net6.0` to be installed.

### CODE REVIEW

**Comment by pjcollins** [comment]
@huangmin-ms Is there anything else I can do to help get this merged?

**Comment by huangmin-ms** [comment]
> @huangmin-ms Is there anything else I can do to help get this merged?

Sorry for the late response, this PR didn't automatically trigger the CI pipeline, I will take a look next week and merge it if CI pipeline passed.

**Comment by huangmin-ms** [comment]
Per security, we cannot build PR from fork repo, so I created https://github.com/mono/api-doc-tools/pull/673 to trigger PR.
And now build is passed, I will merge this PR.

**Review by huangmin-ms — APPROVED** [review]

**Pull request merged**
