### PR TITLE
mdoc: Insert default thread safety information.

### LINKED ISSUE #113: [mdoc] Insert default thread safety information through a custom attribute
Currently, the `<threadsafety>` element is used to describe whether certain types are thread-safe. However, its content has to be manually entered.

The proposal is to have a custom attribute within the element, that will allow tooling that reads ECMAXML to automatically insert boilerplate text, such as `<threadsafe supported="true">`

### PR DESCRIPTION
**Pull request by asokolovskiy15**
Added sample attribute "supported" and complex  "memberScope" with 3 values. Updated file MyClass.xml for integration test "check-monodocer-membergroup"
Closes #113

### CODE REVIEW

**Comment by asokolovskiy15** [comment]
@joelmartinez 
There is a required `<para>` element nested by `<threadsafe>` in the .XSD schema. I've added `<para/>` empty element to the new integration test to make it work. Is this element still required in the .XSD schema?

**Comment by joelmartinez** [comment]
@asokolovskiy15 you can make it optional

**Comment by asokolovskiy15** [comment]
@joelmartinez fixed it.

**Comment by joelmartinez** [comment]
whitelabel

**Comment by joelmartinez** [comment]
build

**Comment by joelmartinez** [comment]
whitelist

**Pull request merged**
