### PR TITLE
Build improvements

### PR DESCRIPTION
**Pull request by sandyarmstrong**
* Replace SharpZipLib submodule with NuGet package
* Replace all packages.config use with `PackageReference`, centralize package versioning
* Change `monodoc.dll` from `net471` to `netstandard2.0`, update csproj to be SDK-style
* Bump `mdoc.Test.FSharp.fsproj` to .NET 4.7.1 to fix issues using `System.ValueTuple`. Also had to convert to SDK-style to fix errors building in VS2022 after change to use `PackageReference`.
* Also convert `mdoc.Test.csproj` to SDK-style since it references the `fsproj`.

### CODE REVIEW

**Comment by sandyarmstrong** [comment]
This includes the changes from https://github.com/mono/api-doc-tools/pull/590.

**Review by Therzok — DISMISSED** [review]

**Comment by Therzok** [comment]
I guess this could supersede 590, given the atomic commit history.

**Review by joelmartinez — CHANGES_REQUESTED** [review]
These are great changes! Only change I'll ask for is to please base these changes on the `develop` branch ... work happens there and is merged into `main` only when a release happens.

**Comment by huangmin-ms** [comment]
@sandyarmstrong I cloned your branch to local but build was failed with below error. Could you help to resolve this?
MicrosoftTeams-image3

**Comment by sandyarmstrong** [comment]
Heh, but now a similar problem is hitting CI. I'll have to convert the the test csproj to SDK-style too, I think.

**Comment by sandyarmstrong** [comment]
@huangmin-ms ok, finally all fixed and green and ready to go. 😄

**Review by huangmin-ms — APPROVED** [review]

**Comment by huangmin-ms** [comment]
@sandyarmstrong  this new change will be pushed to nuget once we merge to main and upgrade our nuget version.  We plan to do the upgrade next week.  We need to follow our release process and will let you know once it is done.

**Comment by huangmin-ms** [comment]
@sandyarmstrong [mdoc 5.8.6](https://www.nuget.org/packages/mdoc/5.8.6) is ready for use, thanks for your contributions!

**Pull request merged**
