### PR TITLE
Updating the Windows metadata files with the latest version and fixed a minor issue in the cpp formatter

### PR DESCRIPTION
**Pull request by JeffInChrist**
Draft PR for #549. Pending for #550  .

### CODE REVIEW

**Review by joelmartinez — CHANGES_REQUESTED** [review]
Hi ... this in general looks fine, but the unit tests are failing in CI. You can run these right in visual studio, so you can quickly iterate locally :)

**Comment by JeffInChrist** [comment]
> Hi ... this in general looks fine, but the unit tests are failing in CI. You can run these right in visual studio, so you can quickly iterate locally :)

@joelmartinez Yup, they are failing in this PR. After #550 is completed, I'll merge the changes and the tests will succeed.

**Comment by joelmartinez** [comment]
@JeffInChrist #550 has now been merged :)

**Comment by JeffInChrist** [comment]
> @JeffInChrist #550 has now been merged :)

Thanks @joelmartinez . I've merged the new changes and finally the CI job has succeeded.

**Review by joelmartinez — APPROVED** [review]

**Pull request merged**
